dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^2.24.3
  firebase_auth: ^4.16.1
  cloud_firestore: ^4.15.0
  
  # UI Helpers
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  
  # Utils
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1